# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- deploy

test:
  image: python:3.7.9
  stage: test
  before_script:
    - pip install -r requirements.txt
  
  when: on_success
  script:
    - python manage.py migrate
    - python manage.py collectstatic --noinput
  only:
    - murungi

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    - gen install dpl
  
  script:
    - dpl --provider=heroku --app=lib-syst --api-key=2e0e9407-1077-432d-a81d-41cf59f00e21

  environment:
    name: main
    url: 
  only:
    - murungi
