# Generated by Django 3.2.12 on 2022-08-24 18:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220716_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=225)),
                ('student_number', models.IntegerField()),
                ('name', models.CharField(max_length=223)),
                ('isbn', models.IntegerField()),
                ('author', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('subject_area', models.CharField(max_length=20)),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(default=base.models.get_expiry)),
            ],
        ),
    ]
